const FIGHTER_DATA = [
  { name: 'Mario' },
  { name: 'Luigi' },
  { name: 'Peach' },
  { name: 'Bowser' },
  { name: 'Dr. Mario' },
  { name: 'Rosalina' },
  { name: 'Bowser Jr.' },
  { name: 'Yoshi' },
  { name: 'Donkey Kong' },
  { name: 'Diddy Kong' },
  { name: 'Link' },
  { name: 'Zelda' },
  { name: 'Sheik' },
  { name: 'Ganondorf' },
  { name: 'Young Link' },
  { name: 'Toon Link' },
  { name: 'Samus' },
  { name: 'Zero Suit Samus' },
  { name: 'Kirby' },
  { name: 'Meta Knight' },
  { name: 'King Dedede' },
  { name: 'Fox' },
  { name: 'Falco' },
  { name: 'Wolf' },
  { name: 'Pikachu' },
  { name: 'Jigglypuff' },
  { name: 'Mewtwo' },
  { name: 'Pichu' },
  { name: 'Pokemon Trainer' },
  { name: 'Lucario' },
  { name: 'Greninja' },
  { name: 'Captain Falcon' },
  { name: 'Ness' },
  { name: 'Lucas' },
  { name: 'Ice Climbers' },
  { name: 'Marth' },
  { name: 'Roy' },
  { name: 'Ike' },
  { name: 'Robin' },
  { name: 'Lucina' },
  { name: 'Corrin' },
  { name: 'Mr. Game & Watch' },
  { name: 'Pit' },
  { name: 'Palutena' },
  { name: 'Dark Pit' },
  { name: 'Wario' },
  { name: 'Olimar' },
  { name: 'R.O.B.' },
  { name: 'Villager' },
  { name: 'Wii Fit Trainer' },
  { name: 'Little Mac' },
  { name: 'Shulk' },
  { name: 'Duck Hunt' },
  { name: 'Snake' },
  { name: 'Sonic' },
  { name: 'Mega Man' },
  { name: 'Pac-Man' },
  { name: 'Ryu' },
  { name: 'Cloud' },
  { name: 'Bayonetta' },
  { name: 'Mii Brawler' },
  { name: 'Mii Swordfighter' },
  { name: 'Mii Gunner' },
  { name: 'Daisy' },
  { name: 'King K. Rool' },
  { name: 'Ridley' },
  { name: 'Dark Samus' },
  { name: 'Incineroar' },
  { name: 'Chrom' },
  { name: 'Isabelle' },
  { name: 'Inkling' },
  { name: 'Ken' },
  { name: 'Simon' },
  { name: 'Richter' },
];


const BOSS_DATA = [
{ name: 'Tricephalos'  },
{ name: 'Gaping Jaw'  },
{ name: 'Sentient Pest'  },
{ name: 'Augur'  },
{ name: 'Equilibrious Beast'  },
{ name: 'Darkdrift Knight'  },
{ name: 'Fissure in the Fog'  },
{ name: 'Night Aspect'  },
];


const ELL_DECKS = [
{ name: 'JP Enchants'  },
{ name: 'Xyris'  },
{ name: 'Rhonas'  },
{ name: 'Raffine'  },
{ name: 'Aurelia'  },
{ name: 'Ghalta & Mavren'  },
{ name: 'Dinosaurs'  },
{ name: 'Beza'  },
{ name: 'Obeka'  },
{ name: 'Ygra'  },
{ name: 'Pirates'  },
{ name: 'Fish'  },
{ name: 'Horror rooms'  },
{ name: 'Ashling'  },
{ name: 'Shadow'  },
{ name: 'Tom'  },
{ name: 'Gandalf'  },
{ name: 'Maha'  },
{ name: 'Scarab god'  },
{ name: 'Glarb'  },

]

const JOSH_DECKS = [
{ name: 'Betor'  },
{ name: 'Breya'  },
{ name: 'Cloud'  },
{ name: 'Double Ds'  },
{ name: 'Dragonlord Ojutai'  },
{ name: 'Gix'  },
{ name: 'God-Eternal Oketra'  },
{ name: 'Hazoret'  },
{ name: 'Inspirit'  },
{ name: 'Jin Gitaxias'  },
{ name: 'Kardur'  },
{ name: 'Lightning'  },
{ name: 'Marneus Calgar'  },
{ name: 'Merfolk'  },
{ name: 'Ms. Bumblebutt'  },
{ name: 'Niv'  },
{ name: 'Niv Reborn'  },
{ name: 'Ruric Thar'  },
{ name: 'Sauron'  },
{ name: 'Shanid'  },
{ name: 'Sin'  },
{ name: 'Squall'  },
{ name: 'Terra'  },
{ name: 'Teysa'  },
{ name: 'Vanille'  },
{ name: 'Velomachus'  },
{ name: 'Vorinclex'  },
{ name: 'Zareth San'  },
{ name: 'Speed Demon'  },

]

const ROB_DECKS = [
{ name: 'Giada'  },
{ name: 'Fynn'  },
{ name: 'Korlash'  },
{ name: 'Muzzio'  },
{ name: 'Krenko'  },
{ name: 'Lathril'  },
{ name: 'Lazav'  },
{ name: 'Edgar'  },
{ name: 'Kaalia'  },
{ name: 'Aminatou'  },
{ name: 'Narset'  },
{ name: 'Marlene'  },
{ name: 'Nekusar'  },
{ name: 'Ghidorah'  },
{ name: 'Atraxa'  },
{ name: 'Aragorn'  },
{ name: 'Omnath'  },
{ name: 'Azlask'  },
{ name: 'Jodah'  },
{ name: 'Ulalek'  },
{ name: 'Anafenza'  },
{ name: 'Jund'  },

]

const ALL_DECKS = [
{ name: 'JP Enchants'  },
{ name: 'Xyris'  },
{ name: 'Rhonas'  },
{ name: 'Raffine'  },
{ name: 'Aurelia'  },
{ name: 'Ghalta & Mavren'  },
{ name: 'Dinosaurs'  },
{ name: 'Beza'  },
{ name: 'Obeka'  },
{ name: 'Ygra'  },
{ name: 'Pirates'  },
{ name: 'Fish'  },
{ name: 'Horror rooms'  },
{ name: 'Ashling'  },
{ name: 'Shadow'  },
{ name: 'Tom'  },
{ name: 'Gandalf'  },
{ name: 'Maha'  },
{ name: 'Scarab god'  },
{ name: 'Glarb'  },

{ name: 'Betor'  },
{ name: 'Breya'  },
{ name: 'Cloud'  },
{ name: 'Double Ds'  },
{ name: 'Dragonlord Ojutai'  },
{ name: 'Gix'  },
{ name: 'God-Eternal Oketra'  },
{ name: 'Hazoret'  },
{ name: 'Inspirit'  },
{ name: 'Jin Gitaxias'  },
{ name: 'Kardur'  },
{ name: 'Lightning'  },
{ name: 'Marneus Calgar'  },
{ name: 'Merfolk'  },
{ name: 'Ms. Bumblebutt'  },
{ name: 'Niv'  },
{ name: 'Niv Reborn'  },
{ name: 'Ruric Thar'  },
{ name: 'Sauron'  },
{ name: 'Shanid'  },
{ name: 'Sin'  },
{ name: 'Squall'  },
{ name: 'Terra'  },
{ name: 'Teysa'  },
{ name: 'Vanille'  },
{ name: 'Velomachus'  },
{ name: 'Vorinclex'  },
{ name: 'Zareth San'  },
{ name: 'Speed Demon'  },

{ name: 'Giada'  },
{ name: 'Fynn'  },
{ name: 'Korlash'  },
{ name: 'Muzzio'  },
{ name: 'Krenko'  },
{ name: 'Lathril'  },
{ name: 'Lazav'  },
{ name: 'Edgar'  },
{ name: 'Kaalia'  },
{ name: 'Aminatou'  },
{ name: 'Narset'  },
{ name: 'Marlene'  },
{ name: 'Nekusar'  },
{ name: 'Ghidorah'  },
{ name: 'Atraxa'  },
{ name: 'Aragorn'  },
{ name: 'Omnath'  },
{ name: 'Azlask'  },
{ name: 'Jodah'  },
{ name: 'Ulalek'  },
{ name: 'Anafenza'  },
{ name: 'Jund'  },

]