const FIGHTER_DATA = [
  { name: 'Mario', p1Fave: true },
  { name: 'Luigi' },
  { name: 'Peach' },
  { name: 'Bowser' },
  { name: 'Dr. Mario' },
  { name: 'Rosalina' },
  { name: 'Bowser Jr.' },
  { name: 'Yoshi' },
  { name: 'Donkey Kong' },
  { name: 'Diddy Kong' },
  { name: 'Link' },
  { name: 'Zelda', p1Fave: true },
  { name: 'Sheik' },
  { name: 'Ganondorf' },
  { name: 'Young Link' },
  { name: 'Toon Link', p2Fave: true },
  { name: 'Samus' },
  { name: 'Zero Suit Samus' },
  { name: 'Kirby' },
  { name: 'Meta Knight' },
  { name: 'King Dedede', p1Fave: true },
  { name: 'Fox' },
  { name: 'Falco', p2Fave: true },
  { name: 'Wolf' },
  { name: 'Pikachu' },
  { name: 'Jigglypuff' },
  { name: 'Mewtwo' },
  { name: 'Pichu' },
  { name: 'Pokemon Trainer' },
  { name: 'Lucario' },
  { name: 'Greninja' },
  { name: 'Captain Falcon' },
  { name: 'Ness', p1Fave: true },
  { name: 'Lucas', p2Fave: true },
  { name: 'Ice Climbers' },
  { name: 'Marth' },
  { name: 'Roy' },
  { name: 'Ike', p1Fave: true, p2Fave: true },
  { name: 'Robin' },
  { name: 'Lucina' },
  { name: 'Corrin' },
  { name: 'Mr. Game & Watch', p1Fave: true },
  { name: 'Pit' },
  { name: 'Palutena' },
  { name: 'Dark Pit' },
  { name: 'Wario' },
  { name: 'Olimar' },
  { name: 'R.O.B.' },
  { name: 'Villager', p1Fave: true },
  { name: 'Wii Fit Trainer' },
  { name: 'Little Mac' },
  { name: 'Shulk' },
  { name: 'Duck Hunt' },
  { name: 'Snake' },
  { name: 'Sonic' },
  { name: 'Mega Man', p2Fave: true },
  { name: 'Pac-Man' },
  { name: 'Ryu' },
  { name: 'Cloud' },
  { name: 'Bayonetta' },
  { name: 'Mii Brawler' },
  { name: 'Mii Swordfighter' },
  { name: 'Mii Gunner' },
  { name: 'Daisy' },
  { name: 'King K. Rool' },
  { name: 'Ridley' },
  { name: 'Dark Samus' },
  { name: 'Incineroar' },
  { name: 'Chrom' },
  { name: 'Isabelle', p2Fave: true },
  { name: 'Inkling' },
  { name: 'Ken' },
  { name: 'Simon' },
  { name: 'Richter' },
];